node {
  def credentialsId = 'git-ssh-key'
  def tf_checkout_dir = 'tf-modules'
  def tf_state_bucket = "${TF_STATE_BUCKET}"

  def operation = "${OPERATION}"

  stage("Checking out TerraForm modules repo") {
    checkout poll:false, scm: [
      $class: 'GitSCM',
      branches: [[name: "${TF_GIT_BRANCH}"]],
      extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: tf_checkout_dir ]],
      submoduleCfg: [],
      userRemoteConfigs: [[url: "${TF_GIT_URL}", credentialsId: credentialsId]]
      ]
  }

  stage("Install Terraform") {
    terraform_install()
  }

  stage("Terraform deployment of the VPC infrastructure") {
    try {
      dir(tf_checkout_dir) {
        println("Initializing terraform execution")
        ansiColor('xterm') {
          sh("""${JENKINS_HOME}/custom_tools/terraform init -input=false -backend-config="bucket=${TF_STATE_BUCKET}" -backend-config="region=${REGION}" """)
        }

        println("Validating terraform template syntax")
        ansiColor('xterm') {
          sh("""${JENKINS_HOME}/custom_tools/terraform validate -check-variables=true""")
        }

        println("Generating Terraform Plan")
        ansiColor('xterm') {
          sh("""${JENKINS_HOME}/custom_tools/terraform plan -input=false -out=plan.out -detailed-exitcode """)
        }
      }
    }
    catch(err) {
      println(err)
    }
    finally {
      deleteDir()
    }
  }
}

def terraform_install() {
  sh("""
  #! /bin/bash

  if [ ! -d ${JENKINS_HOME}/custom_tools ]; then
     mkdir -p ${JENKINS_HOME}/custom_tools
  fi

  if [ ! -f ${JENKINS_HOME}/custom_tools/terraform ]; then
     sudo apt install -y unzip jq
     TERRAFORM_VERSION=\$(curl https://api.github.com/repos/hashicorp/terraform/releases/latest | jq '.tag_name' | tr -d '"' | tr -d v)
     DOWNLOAD_URL=https://releases.hashicorp.com/terraform/\${TERRAFORM_VERSION}/terraform_\${TERRAFORM_VERSION}_linux_amd64.zip
     echo \$TERRAFORM_VERSION
     curl -o /tmp/terraform_\$TERRAFORM_VERSION.zip \$DOWNLOAD_URL
     unzip /tmp/terraform_\$TERRAFORM_VERSION.zip -d $JENKINS_HOME/custom_tools
     echo "plugin_cache_dir   = \\"$JENKINS_HOME/.terraform.d/plugin-cache\\"" > $JENKINS_HOME/.terraformrc
  fi
   """)
}
